services:
  - type: web
    name: frontend-luxepass
    env: node
    plan: free
    root: .
    buildCommand: yarn install --frozen-lockfile && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
